### ISSUE TITLE
프로젝트 리드미 작성

### ISSUE THREAD

**Issue by seungjaeshina** [HMDandelion/project1-4-1000-2_back#2]
---
name: 프로젝트 리드미 초안
about: 리드미 문서 작성
title: "프로젝트 리드미"
labels: 문서, 기능 개선, 도움 요청, 수정 요청
assignees: ''

---

**이슈 유형**

- [ ] 문서 개선

**설명**
리드미 (초본) 작성

- 프로젝트 소개
- 설치 방법
- 구동 방법
- 기여 방법
- 라이선스

**목표**
일사천리 프로젝트를 보다 쉽게 이해할 수 있는 설명 작성

**Comment by eurdream98** [comment]
잘 시작해봅시다~
