### ISSUE TITLE
[FEATURE] 상품 관리 구현 

### ISSUE THREAD

**Issue by eurdream98** [HMDandelion/project1-4-1000-2_back#6]
---
name: 기능 개발
about: 새로운 기능 개발에 대한 이슈 작성
title: "[FEATURE] "
labels: 기능 개발
assignees: ''

---

**기능 설명**
상품 관리 기능 구현

**필요성**
상품 관리 기능을 만들어 상품에 대한 정보를 제공

**기능 요구사항**
- [x] 상품 조회(필터 검색 기능 및 전체 조회)
- [x] 상품 등록
- [x] 상품 상세 조회(상품 코드에 맞는 상품 조회)
- [x] 상품 수정
- [x] 상품 삭제

**기술 사양**
기능 구현에 필요한 기술적 사양이나 고려사항을 명시해주세요.
- 예: API 엔드포인트, 데이터베이스 스키마 변경 등

**관련 자료**
기능 개발에 참고할 만한 자료(링크, 문서 등)를 추가해주세요.
- 링크 1
- 링크 2

**추가 정보**
기능 개발에 필요한 추가 정보나 맥락을 작성해주세요.

**Comment by MIdWit0828** [comment]
종료
